before_script:
  - echo "Running on - `date`"

types:
  - simple-deploy

job_deploy_aws:
  type: simple-deploy
  script:
  - rm -fr node_modules/
  - npm install
  - npm run build
  - rm -fr /var/www/html/*
  - cp -fr build/* /var/www/html/
  - service nginx restart
  only:
  - master
  tags:
  - sov
  - chuck
